apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion COMPILE_SDK
    buildToolsVersion BUILD_TOOLS_VERSION

    defaultConfig {
        applicationId "amirz.shade.phonebridge"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${KOTLIN_VERSION}"
    implementation "org.java-websocket:Java-WebSocket:${JAVA_WEBSOCKET_VERSION}"
    implementation "androidx.activity:activity-ktx:${ANDROID_X_ACTIVITY_VERSION}"
    implementation "androidx.lifecycle:lifecycle-service:${LIFECYCLE_VERSION}"
}
